### ISSUE TITLE
File Manager > 2GB

### ISSUE THREAD

**Issue by thdal** [quasar/QuasarRAT#759] opened 2019-02-26 11:56 UTC
Hi Maxxor, I have been trying on different version of Quasar and every time when I try to download a file of more that 2 GB with the file manager I had an error "unable to read from File Stream" or "error reading file" in function of quasar's version. So is that the limit you've set? It's possible to do better.

hoping for an answer,
Cordialy

**Comment by MaxXor** [comment] 2019-03-03 21:40
There is no limitation, but it takes a while to transfer such a big file. The implemented file transfer is not the fastest. :smile:  When exactly does it happen? In the middle of transferring the file or right at the beginning? Couldn't reproduce it yet with a 4GB file.

**Comment by DannyTheSloth** [comment] 2019-05-17 00:57
This issue would require some work from the developers to be fixed. It is caused by the maximum size of an array (an array of bytes that makes up the file data), the default value for this array is 2,147,483,647 bytes, or 2 GB. Therefor, it can not read files larger than 2 GB.

**Comment by MaxXor** [comment] 2019-05-17 06:38
Lol, Quasar doesn't read the whole file into an array.

**Comment by DannyTheSloth** [comment] 2019-05-17 20:57
Oh I see, it reads in chunks. My bad.

**Closed** 2020-05-31 14:52 UTC
