### ISSUE TITLE
[suggestion] add process protection

### ISSUE THREAD

**Issue by hackereg35** [quasar/QuasarRAT#478] opened 2016-07-07 10:28 UTC
how about adding a process protection, because the client can be killed from the Task Manager,
but in "NJrat" if the user tried to kill the process he gets a bluescreen

**Comment by MaxXor** [comment] 2016-07-07 11:24
Duplicate of https://github.com/quasar/QuasarRAT/issues/388

**Closed by MaxXor** 2016-07-07 11:24 UTC
Labels: duplicate
