### ISSUE TITLE
Backdoor

### ISSUE THREAD

**Issue by wjkhappy14** [quasar/QuasarRAT#680] opened 2018-07-07 08:03 UTC
launch warn "Backdoor"

Windows Defender    [backdoor：Win32/Xiclog.A]

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Backdoor%3aWin32%2fXiclog.A&threatid=2147721343

**Comment by MaxXor** [comment] 2018-07-07 08:48
Duplicate of https://github.com/quasar/QuasarRAT/issues/676

**Closed by MaxXor** 2018-07-07 08:48 UTC
