### ISSUE TITLE
Client.bin file missing

### ISSUE THREAD

**Issue by HiItsMeHaHa** [quasar/QuasarRAT#565] opened 2016-12-14 16:37 UTC
when I run the client builder, it tells me "client.bin" is missing.  I'm on windows 10.  I checked the Bin folder, and there didn't seem to be a file entitled "client.bin" (though there was a client folder).  I'm sure this is an issue with me, and not the RAT, but I don't know how to fix it.

**Comment by MaxXor** [comment] 2016-12-14 16:40
Duplicate of #552, #508, #452, etc...

**Closed by MaxXor** 2016-12-14 16:40 UTC
Labels: duplicate

**Comment by HiItsMeHaHa** [comment] 2016-12-15 03:24
#508 and #452 are irrelevant because they're different OS, and turning off my anti-malware didn't fix it.  Also, the client.bin file isn't in the zip either.

**Comment by MaxXor** [comment] 2016-12-15 15:22
They are in every release here: https://github.com/quasar/QuasarRAT/releases
